### ISSUE TITLE
tern repeatedly timing out trying to parse ramda.js

### ISSUE THREAD

**Issue by gilligan** [marijnh/tern#570] opened 2015-06-25 21:12 UTC
##### What
Using tern via `tern_for_vim` I repeatedly run into timeouts and vim gets stuck during completions when I require ramda : `https://github.com/ramda/ramda/tree/master/dist`

##### How

```javascript
var R = require('ramda');
R.
```
Triggering code completion with the buffer contents above will almost consistently 
yield a timeout ("timed out" in command line).

##### Specs
- latest tern_for_vim
- vim 7.4 1-488
- nvim from master

**Comment by marijnh** [comment] 2015-06-26 13:34
I can reproduce this -- it takes about 18 seconds to process ramda.js. This file is both huge and doing lots of things that are expensive to analyze (most functions are higher-order, requiring re-instantiation for every call). Tern currently doesn't have a mechanism for gracefully handling a situation like this, and I'm not sure what such a mechanism would look like.

It might be possible to move to a scheme where dependencies get alloted a certain time budget, and if they time out the analyzer just skips that dependency and moves on. But I do not have time to implement this on the short term.

**Comment by gilligan** [comment] 2015-06-26 18:22
@marijnh Alright, I thought it might be something like that. 
I only have 2 quick questions : 

1. I ran `condense` on ramda and added the resulting definition file to my tern config. I
thought given the definition tern would not parse ramda again and just stick to the definition which would speed things up ? I think I might be misunderstanding something.

2. Just requiring ramda makes vim/tern completely unusable. It might be good if there was a way to blacklist certain packages ? I could do without completions for ramda. Right now I just can't use tern at all in projects where I use ramda.

**Comment by marijnh** [comment] 2015-06-26 19:35
Probably the problem is with file name normalization -- the node plugin will look for files by absolute path, and you probably passed a relative path to `condense`, preventing the plugin from figuring out that this is the same file. I think you can solve this by simply passing the whole path to the file. (I know this is suboptimal, this is an area that hasn't seen much use and thought yet.)

**Comment by gilligan** [comment] 2015-07-16 19:42
@marijnh Sorry I think I need some help with this:
```
$ condense node_modules/ramda/dist/ramda.js > ramda.json
```
The output is saved to `tern/defs` and I added 'ramda' to the .tern-project configuration : 
`plugins: [ 'ramda' ]`

So at the top of ramda.json : 
```
"!name": "node_modules/ramda/dist/ramda.js",
```

Am I doing something wrong ? I don't get any completions at all.

**Comment by marijnh** [comment] 2015-07-16 20:17
That's still not an absolute path (like say, `"/home/gilligan/src/my_project/node_modules/ramda/dist/ramda.js"`)

**Comment by angelozerr** [comment] 2015-07-17 07:54
You  must use libs instead of plugins in your .tern-project

**Comment by gilligan** [comment] 2015-07-17 21:03
@marijnh argh yes .. absolute.... okay that is almost useless then. Would have to modify that each time i switch the project.

@angelozerr errr.. yes. of course! ;-)

**Comment by gilligan** [comment] 2015-10-14 07:59
Sorry to revive this but is just bugging me quite a lot. I created a `ramda.json` definition created by condense and tern is actually parsing and sometimes it is working fine and in some files I just constantly run into timeouts with anything I try to complete. 

@marijnh I seem to remember that you mentioned there is some way to blacklist modules ? I could not find anything in the documentation. Could you help me out with that ? I'm hoping everything will just work if I blacklist ramda.

**Comment by marijnh** [comment] 2015-10-16 13:15
Adding a `dontLoad: ["path/to/ramda.js"]` to your `.tern-project` should work.

But, partly in response to this thread, recent versions of Tern have started using project-relative paths to identify files. So now if you run `condense` from your project dir and autoload the resulting json, it should already replace the script file automatically. (And the thing I recommended before, using an absolute path, won't work anymore.)

**Comment by gilligan** [comment] 2015-10-18 14:46
@marijnh Thank you. The combination of adding ramda to `dontLoad` and adding a ramda.json created by condense is a working solution for me for now. Should this ticket be closed ? Early on you mentioned something about possibly opting out when traversals go to deep / too time consuming but of course this is not in any way directly related to ramda anyway. TL;DR : feel free to close this is you think its appropriate.

**Comment by marijnh** [comment] 2015-10-27 15:58
Closing, since I still don't really have a good plan for the traversal cut-off idea.

**Closed by marijnh** 2015-10-27 15:58 UTC

**Comment by haakenlid** [comment] 2017-09-03 11:13
How did you get a proper definition file for ramda with condense? I've attempted this

    node_modules/tern/bin/condense --plugin doc_comment={strong: true} /
        node_modules/ramda/dist/ramda.js > ramda.doc_comments.json

This was the best result I could get. I'm using the latest version of ramda (0.24.1) and ternjs (0.21.0).

https://gist.github.com/haakenlid/1eccbc70a6394ec12c79c5c32a009292

It doesn't contain all functions, and most are missing doc strings and signatures . 

A few functions get proper definitions. 
```
"pipeP": {
      "!type": "fn() -> +Function",
      "!span": "318890[9302:8]-318895[9302:13]",
      "!doc": "Performs left-to-right composition of one or more Promise-returning\nfunctions. The leftmost function may have any arity; the remaining functions\nmust be unary.\n\n@func\n@memberOf R\n@since v0.10.0\n@category Function\n@sig ((a -> Promise b), (b -> Promise c), ..., (y -> Promise z)) -> (a -> Promise z)\n@param {...Function} functions\n@return {Function}\n@see R.composeP\n@example\n\n     //  followersForUser :: String -> Promise [User]\n     var followersForUser = R.pipeP(db.getUserById, db.getFollowers);"
    },
```

But most look like this: 
```
    "addIndex": "+Function",
    "adjust": "+Function",
    "all": "+Function",
    "allPass": "+Function"
    ... etc
```

And some are missing altogether, for example `hasOwnProperty`. 

But if I don't use the defs file, everything shows up, though a lot are missing docs and the types are all wrong. Here's an example in vim:

![image](https://user-images.githubusercontent.com/1686266/30002380-59612c06-90a8-11e7-8742-67c8c275cd3e.png)

Unfortunately, without the defs file, tern is very slow and flaky when it comes to ramda, as discussed previously in this issue.

What I want is to condense a complete definition file for ramda.js. Preferably with a automated tool such as condense. Writing a defs file manually is also feasible, but it would be a pain to keep up with any future changes in ramda. 

There's a repo for typescript definitions for ramda, but I'm not sure if it's possible to convert that to tern's format. https://github.com/types/npm-ramda

**Comment by haakenlid** [comment] 2017-09-03 11:33
Here's the source of some of the functions I mentioned. Presumably the problem is that ramda is using higher order functions such as `curry` all over the place. I can see why it's complicated to infer the proper type signatures. But it would be nice to get the docstrings right.

[R.pipeP](https://github.com/ramda/ramda/blob/1242d85c14dbfe5c6e795c78534a5188ef9c7f61/dist/ramda.js#L7940) Is processed fine by condense

```javascript
    /**
     * Performs left-to-right composition of one or more Promise-returning
     * functions. The leftmost function may have any arity; the remaining functions
     * must be unary.
     *
     * @func
     * @memberOf R
     * @since v0.10.0
     * @category Function
     * @sig ((a -> Promise b), (b -> Promise c), ..., (y -> Promise z)) -> (a -> Promise z)
     * @param {...Function} functions
     * @return {Function}
     * @see R.composeP
     * @example
     *
     *      //  followersForUser :: String -> Promise [User]
     *      var followersForUser = R.pipeP(db.getUserById, db.getFollowers);
     */
    var pipeP = function pipeP() {
        if (arguments.length === 0) {
            throw new Error('pipeP requires at least one argument');
        }
        return _arity(arguments[0].length, reduce(_pipeP, arguments[0], tail(arguments)));
    };

```

[R.addIndex](https://github.com/ramda/ramda/blob/1242d85c14dbfe5c6e795c78534a5188ef9c7f61/dist/ramda.js#L5513) does not get a docstring


```javascript
   /**
     * Creates a new list iteration function from an existing one by adding two new
     * parameters to its callback function: the current index, and the entire list.
     *
     * This would turn, for instance, [`R.map`](#map) function into one that
     * more closely resembles `Array.prototype.map`. Note that this will only work
     * for functions in which the iteration callback function is the first
     * parameter, and where the list is the last parameter. (This latter might be
     * unimportant if the list parameter is not used.)
     *
     * @func
     * @memberOf R
     * @since v0.15.0
     * @category Function
     * @category List
     * @sig ((a ... -> b) ... -> [a] -> *) -> (a ..., Int, [a] -> b) ... -> [a] -> *)
     * @param {Function} fn A list iteration function that does not pass index or list to its callback
     * @return {Function} An altered list iteration function that passes (item, index, list) to its callback
     * @example
     *
     *      var mapIndexed = R.addIndex(R.map);
     *      mapIndexed((val, idx) => idx + '-' + val, ['f', 'o', 'o', 'b', 'a', 'r']);
     *      //=> ['0-f', '1-o', '2-o', '3-b', '4-a', '5-r']
     */
    var addIndex = _curry1(function addIndex(fn) {
        return curryN(fn.length, function () {
            var idx = 0;
            var origFn = arguments[0];
            var list = arguments[arguments.length - 1];
            var args = Array.prototype.slice.call(arguments, 0);
            args[0] = function () {
                var result = origFn.apply(this, _concat(arguments, [
                    idx,
                    list
                ]));
                idx += 1;
                return result;
            };
            return fn.apply(this, args);
        });
```

[R.ascend](https://github.com/ramda/ramda/blob/1242d85c14dbfe5c6e795c78534a5188ef9c7f61/dist/ramda.js#L1255) does not get a docstring in any case.

```javascript
   /**
     * Makes an ascending comparator function out of a function that returns a value
     * that can be compared with `<` and `>`.
     *
     * @func
     * @memberOf R
     * @since v0.23.0
     * @category Function
     * @sig Ord b => (a -> b) -> a -> a -> Number
     * @param {Function} fn A function of arity one that returns a value that can be compared
     * @param {*} a The first item to be compared.
     * @param {*} b The second item to be compared.
     * @return {Number} `-1` if fn(a) < fn(b), `1` if fn(b) < fn(a), otherwise `0`
     * @see R.descend
     * @example
     *
     *      var byAge = R.ascend(R.prop('age'));
     *      var people = [
     *        // ...
     *      ];
     *      var peopleByYoungestFirst = R.sort(byAge, people);
     */
    var ascend = _curry3(function ascend(fn, a, b) {
        var aa = fn(a);
        var bb = fn(b);
        return aa < bb ? -1 : aa > bb ? 1 : 0;
    });

```
