### ISSUE TITLE
Wrong file position

### ISSUE THREAD

**Issue by kimgronqvist** [marijnh/tern#467] opened 2015-01-05 14:19 UTC
In emacs (24.4, Windows 8 64-bit) Tern gets gets out of sync in the file after a couple of lines. I get this behaviour in all files, but here's an example from the tern code base.

Here everything is okay:
![image](https://cloud.githubusercontent.com/assets/3421067/5613965/f3887d0e-94eb-11e4-9aa0-37bc92143078.png)

But further down I get this:
![image](https://cloud.githubusercontent.com/assets/3421067/5614138/18ee2344-94ee-11e4-8bcc-f235a54bd88a.png)

I also get message like this one when I try to use tern-find-defintion:
`error in process filter: tern-find-position: Args out of range: #<buffer tern.js>, 35027, 35077`

**Comment by kiwanami** [comment] 2015-01-05 17:35
Which coding of end of line do you use?
I met similar troubles during editing for `utf8-dos` coding system, too.

It may be caused by the difference of handling EOL between Emacs and node.js, Emacs treats CRLF as one character, but node.js does as 2 characters.
The difference arises when node.js reads source codes which are opened by Emacs or required by some source codes.
If a source code is modified in Emacs, the modified code is sent to node.js from Emacs. In this case, because the EOL codes correspond, I don't meet the problem.

Deleting CR code when file reading, I confirmed that this problem is resolved.
I modified `updateText` function in `lib/tern.js`, like following:
https://github.com/marijnh/tern/blob/9ecb8285580a049b0e91c28cdcc350c02b2f62ee/lib/tern.js#L75
```
  function updateText(file, text, srv) {
    file.text = text.replace(/\r/g,""); // adjust text position to editor
    file.ast = infer.parse(file.text, srv.passes, {directSourceFile: file, allowReturnOutsideFunction: true});
    file.lineOffsets = null;
  }
```

But, I don't know whether this code is OK even in the other text editors, such as vim, ST and browser's editors.

**Comment by kimgronqvist** [comment] 2015-01-07 00:06
I might have spoken to soon :) Switching to utf8-unix fixes the problem, but the change to updateText doesn't seem to make any difference.

**Comment by kiwanami** [comment] 2015-01-07 00:28
I may miss some cause...

Will you check the diff? I modified two lines:
```diff
diff --git a/lib/tern.js b/lib/tern.js
index 628a3e0..ddc3886 100644
--- a/lib/tern.js
+++ b/lib/tern.js
@@ -73,8 +73,8 @@
   File.prototype.asLineChar = function(pos) { return asLineChar(this, pos); };
 
   function updateText(file, text, srv) {
-    file.text = text;
-    file.ast = infer.parse(text, srv.passes, {directSourceFile: file, allowReturnOutsideFunction: true});
+    file.text = text.replace(/\r/g,""); // adjust text position to editor
+    file.ast = infer.parse(file.text, srv.passes, {directSourceFile: file, allowReturnOutsideFunction: true});
     file.lineOffsets = null;
   }
```

**Comment by kimgronqvist** [comment] 2015-01-07 09:39
Doh, I missed the second line :) Thanks!

**Comment by kiwanami** [comment] 2015-01-09 10:30
It's good news!

I have also checked that this deleting CR code does not break the functions with gvim on windows8 and linux. So, I'll make a PR later.

@kimgronqvist, will you close this issue?

**Closed** 2015-01-09 10:41 UTC
